export const HOTELS = [
  {
    key: "ranginui",
    name: "Ranginui at Lake Tekapo",
    engine: "staah",
    checkIn: "2027-02-05",
    checkOut: "2027-02-06",
    adults: 2,
    bookingUrl:
      "https://bookdirect.prenohq.com/inst/#home?propertyId=262IjuXNAH9B7SD4LIUyNzU5NiI=&JDRN=Y",
    propertyId: "262IjuXNAH9B7SD4LIUyNzU5NiI=",
    apiKey: "cPPq1uh0xD6BpfDFpGWEx9fxnDOUA3Y25RdigC0X",
  },
  {
    key: "grand-suites",
    name: "Grand Suites Lake Tekapo",
    engine: "ibex",
    checkIn: "2027-02-05",
    checkOut: "2027-02-06",
    adults: 2,
    bookingUrl: "https://grandsuitestekapo.co.nz/book-now/",
    propertyId: "12972",
    client: "grandtekapo",
    clientKey: "grandtekapo653666a9080e6265",
    referrer: "grandsuitestekapo.co.nz",
  },
  {
    key: "peppers-bluewater",
    name: "Peppers Bluewater Resort Lake Tekapo",
    engine: "accor",
    checkIn: "2027-02-05",
    checkOut: "2027-02-06",
    adults: 2,
    bookingUrl: "https://all.accor.com/booking/en/accor/hotel/B3Q7",
    hotelId: "B3Q7",
    apiKey: "l7xx5b9f4a053aaf43d8bc05bcc266dd8532",
  },
  {
    key: "hermitage-mt-cook",
    name: "The Hermitage Hotel Mt Cook",
    engine: "agilysys",
    checkIn: "2027-02-05",
    checkOut: "2027-02-06",
    adults: 2,
    bookingUrl: "https://book.hermitage.co.nz/onecart/wbe/offers/20104/hermitage",
    tenantId: "20104",
    propertyId: "hermitage",
    contextId: "686b116fd8b56d477136cd1d",
    offerCode: "DYNRO",
  },
  {
    key: "tasman-hahei-beach",
    name: "Tasman Holiday Parks Hahei Beach",
    engine: "newbook",
    checkIn: "2027-02-12",
    checkOut: "2027-02-13",
    adults: 2,
    bookingUrl: "https://book.tasmanholidayparks.com/hahei-beach/",
    endpoint:
      "https://book.tasmanholidayparks.com/wp-content/themes/newbookcrs-child/newbook/hahei-beach/api.php?newbook_api_action=availability_chart_responsive",
  },
];

export const BROWSER_ONLY_HOTELS = ["lakeview-tekapo", "galaxy-boutique"];
